function net = mnist_cnn_initialize_sample()

rng(1000);
lr = [.1 2] ; % learning rate for weights and bias

% Define network
net.layers = {} ;

% Layer 1 -- First Convolutional Layer
net.layers{end+1} = struct('type', 'conv', ...
    'weights', {{0.01*randn(5,5,1,32, 'single'), zeros(1, 32, 'single')}}, ...
    'learningRate', lr, ...
    'stride', 1, ...
    'pad', 2) ;
% Layer 2
net.layers{end+1} = struct('type', 'relu') ;
% Layer 3
net.layers{end+1} = struct('type', 'pool', ...
    'method', 'max', ...
    'pool', [2 2], ...
    'stride', 2, ...
    'pad', [0 0 0 0]);
% Layer 4 -- Second Convolutional Layer
net.layers{end+1} = struct('type', 'conv', ...
    'weights', {{0.05*randn(5,5,32,32, 'single'), zeros(1,32,'single')}}, ...
    'learningRate', lr, ...
    'stride', 1, ...
    'pad', 2) ;
% Layer 5
net.layers{end+1} = struct('type', 'relu') ;
% Layer 6
net.layers{end+1} = struct('type', 'pool', ...
    'method', 'max', ...
    'pool', [2 2], ...
    'stride', 2, ...
    'pad', [0 0 0 0]) ;
% Layer 7 -- Third Convolutional Layer (Fully Connected Layer)
net.layers{end+1} = struct('type', 'conv', ...
    'weights', {{0.05*randn(5,5,32,32, 'single'), zeros(1,32,'single')}}, ...
    'learningRate', .1*lr, ...
    'stride', 2, ...
    'pad', 0) ;
% Layer 8
net.layers{end+1} = struct('type', 'relu') ;
% Layer 9
net.layers{end+1} = struct('type', 'conv', ...
    'weights', {{0.05*randn(1,1,32, 10, 'single'), zeros(1,10,'single')}}, ...
    'learningRate', .1*lr, ...
    'stride', 1, ...
    'pad', 0) ;
% Loss layer no. 10
net.layers{end+1} = struct('type', 'softmaxloss') ;


